name: Deploy to PyPI on release

on:
  release:
    types: [published]

jobs:
  deploy_pypi:
    if: ${{ github.repository == 'MuPT-Hub/mupt' }}
    runs-on: ubuntu-latest
    name: Deploy to PyPI on release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.x'
      - run: |
          python -m pip install twine build wheel
        name: Install release tools
      - run: |
          python -m build --sdist --wheel
        name: "Build package"
      - run: |
          twine check dist/*
        name: Check package
      - uses: pypa/gh-action-pypi-publish@release/v1
        name: Upload to PyPI